name: バグ対応テンプレート
description: バグを報告するためのテンプレートです。
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        以下の項目を埋めてください。

  - type: textarea
    id: what-is-happening
    attributes:
      label: 発生していること
      description: バグの詳細を記述してください。
      placeholder: バグの内容を記述してください。
    validations:
      required: true

  - type: textarea
    id: cause
    attributes:
      label: 原因
      description: バグの発生原因を記述してください。
      placeholder: 原因を記述してください。
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 再現方法
      description: バグの再現方法を記述してください。
      placeholder: 再現手順を記述してください。
    validations:
      required: true

  - type: input
    id: reporter
    attributes:
      label: 依頼元(者)
      description: バグの発見者報告者を記述してください。
      placeholder: 報告者の名前を記述してください。
    validations:
      required: false

  - type: textarea
    id: not-in-scope
    attributes:
      label: やらないこと
      description: この対応でやらないことを記述してください。
      placeholder: スコープ外の内容を記述してください。
    validations:
      required: false

  - type: textarea
    id: done-condition
    attributes:
      label: 完了条件
      description: このタスクの完了条件を記述してください。
      placeholder: 完了条件を記述してください。
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 参考資料
      description: 外部資料などを添付してください。
      placeholder: 参考になるリンクやドキュメントを記述してください。
    validations:
      required: false
